# Generated by Django 3.0.6 on 2020-05-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='search',
            field=models.CharField(default='', max_length=255),
        ),
    ]
