# Generated by Django 3.0.6 on 2020-05-13 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_history_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 19, 49, 23, 94563, tzinfo=utc)),
        ),
    ]
