# Generated by Django 3.0.6 on 2020-05-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200515_1658'),
        ('user_profile', '0005_auto_20200515_1453'),
    ]

    operations = [
    ]
