# Generated by Django 3.0.6 on 2020-05-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain_console', '0002_auto_20200513_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
