# Generated by Django 3.0.6 on 2020-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_console', '0004_auto_20200506_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='captain_console.Product'),
        ),
    ]
