# Generated by Django 3.0.6 on 2020-05-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain_console', '0006_auto_20200506_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
