# Generated by Django 3.0.6 on 2020-05-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_console', '0007_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, default=0, to='captain_console.Product'),
        ),
    ]
