# Generated by Django 3.0.6 on 2020-05-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain_console', '0010_auto_20200507_2006'),
        ('captain_console', '0003_userimage'),
    ]

    operations = [
    ]
